//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Registro
    {
        public int ID_Solicitud_registro { get; set; }
        public int ID_Usuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
