//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Solicitud_Insumos = new HashSet<Solicitud_Insumos>();
            this.Solicitud_Registro = new HashSet<Solicitud_Registro>();
        }
    
        public int ID_Usuario { get; set; }
        public string NombreCompleto { get; set; }
        public string Contrasena { get; set; }
        public string Correo { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> Numero_Tele { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Insumos> Solicitud_Insumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Registro> Solicitud_Registro { get; set; }
    }
}
